apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: | 
    <html>
    <head><title>Welcome</title></head>
    <body>
    <h1>Welcome to Nginx !</h1>
    </body>
    </html>
